url: https://gdgostrava.github.io/gdg-garage/
baseurl: /gdg-garage

# Site settings
title: GDG Garage
email: macinda@gmail.com
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Marcel Laza
  pic: Marcel
  position: test
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Filip Goszler
  pic: 2
  position: test
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/GXG_Ostrava
  - title: facebook
    url: https://www.facebook.com/gxgostrava
  - title: github
    url: https://github.com/GDGOstrava

# Postal address (add as many lines as necessary)
address:

  - line: Ostrava

# Build settings
markdown: kramdown
permalink: pretty