url: https://gdgostrava.github.io/gdg-garage/
baseurl: /gdg-garage

# Site settings
title: GDG Garage
email: macinda@gmail.com
description: ""


exclude: [css. style.css]
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Marcel Laza
  pic: marcel
  position: GDG Org
  social:
    - title: twitter
      url: https://twitter.com/lazamarcel
    - title: linkedin
      url: https://www.linkedin.com/pub/marcel-laza/45/763/427

- name: Filip Goszler
  pic: filip
  position: GDG Org
  social:
    - title: twitter
      url: https://twitter.com/FilipGoszler
    - title: linkedin
      url: cz.linkedin.com/pub/filip-goszler/57/372/9a0/en

participants:
- name: You
  pic: wewantyou
  position: SW blaster
  social:
    - title: twitter
      url: #
    - title: stack-overflow
      url: #

- name: You
  pic: wewantyou
  position: HW Guru
  social:
    - title: twitter
      url: #
- name: You
  pic: wewantyou
  position: Mr. Possible
  social:
    - title: twitter
      url: #
- name: You
  pic: wewantyou
  position: I can do that!
  social:
    - title: twitter
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/GXG_Ostrava
  - title: facebook
    url: https://www.facebook.com/gxgostrava
  - title: github
    url: https://github.com/GDGOstrava

# Postal address (add as many lines as necessary)
address:

  - line: Ostrava

# Build settings
markdown: kramdown
permalink: pretty